# py-kms Server Configuration

# Server Network Settings
server:
  ip: "0.0.0.0"  # The IP address to listen on (all interfaces)
  port: 1688  # Default KMS port
  backlog: 5  # Connection backlog
  reuse: true  # Allow address reuse
  dual: false  # IPv6 dual stack support
  timeout:
    idle: null  # Maximum inactivity time (seconds)
    send_receive: null  # Maximum time for send/receive (seconds)
  additional_listeners: []  # Additional IP:port combinations to listen on
    # Format: 
    # - address: "192.168.1.10"
    #   port: 1688
    #   backlog: 5
    #   reuse: true

# KMS Emulator Settings
kms:
  # Enterprise PID (EPID) Configuration
  # If null, a random EPID will be generated based on the client request
  # If specified, must match format: XXXXX-XXXXX-XXX-XXXXXX-XX-XXXX-XXXX.0000-XXXXXXX
  # Where:
  # - Part 1: Platform ID (5 digits, e.g. 03612)
  # - Part 2: Group ID (5 digits, e.g. 00206)
  # - Part 3: Product Key ID Part 1 (3 digits)
  # - Part 4: Product Key ID Part 2 (6 digits)
  # - Part 5: License Channel (2 digits, must be 03 for Volume)
  # - Part 6: Language Code/LCID (4 digits, e.g. 1033 for en-US)
  # - Part 7: KMS Server OS Build (4 digits + .0000)
  # - Part 8: Activation Date (3 digits for day + 4 digits for year)
  # Example: 03612-00206-568-381813-03-1033-14393.0000-2702018
  epid: null
  
  # Language Code ID (LCID)
  # Used for EPID generation when no EPID is specified
  # Common values:
  # - 1033: English - United States (default)
  # - 1034: Spanish - Spain
  # - 1036: French - France
  # - 1031: German - Germany
  # - 1041: Japanese - Japan
  # See: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/
  lcid: 1033
  
  hwid: "364F463A8863D35F"  # Hardware ID or "RANDOM"
  client_count: null  # Minimum clients needed (≥25 for client OS, ≥5 for server/office)
  intervals:
    activation: 120  # Minutes between activation attempts
    renewal: 10080  # Minutes between renewal attempts (7 days)

# Database Settings
database:
  type: "sqlite"  # sqlite, mysql, or postgresql
  name: "sqlite:///pykms_database.db"  # Database name/path
  host: "localhost"  # Database host (for MySQL/PostgreSQL)
  user: ""  # Database username
  password: ""  # Database password

# Web Interface Settings
web_gui:
  enabled: false  # Enable web-based GUI
  port: 8080  # Web interface port

# Logging Configuration
logging:
  level: "ERROR"  # CRITICAL, ERROR, WARNING, INFO, DEBUG, MININFO
  file: "pykms_logserver.log"  # Log file path or special values:
    # STDOUT - Log to console
    # FILESTDOUT - Log to both file and console
    # STDOUTOFF - Disable console output
    # FILEOFF - Disable file logging
  max_size: 0  # Maximum log file size in MB (0 = unlimited) 