#!/bin/sh /etc/rc.common
# Script to start py-kms automatically on OpenWRT
# Ensure you cloned py-kms into /root (~ as the root user)

START=77

start()	{
	sleep 5 # ensure the boot process is complete
	. /etc/profile
	HOST_IP=$(ip a s br-lan | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}/24\b")
	HOST_IP=${HOST_IP%???}
	python /root/py-kms-1/py-kms/pykms_Server.py $HOST_IP 1688 >> /root/py-kms-1/kms.log &
	echo "Python KMS server started on "$HOST_IP":1688"
}

stop()	{
	PID=$(ps | grep '[p]ython /root/py-kms-1/py-kms/pykms_Server.py' | awk '{ print $1 }')
	echo "Found process with ID "$PID
	kill $PID
	sleep 2
	echo "Python KMS server (PID"$PID") stopped"
}